# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-21 07:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ussd_string', models.CharField(max_length=150, null=True)),
                ('name', models.CharField(default='Church Name', max_length=100)),
                ('contact_details', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('banking_details', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('published', models.BooleanField(default=True)),
                ('church', models.ManyToManyField(to='BookingUssd.Church')),
            ],
        ),
        migrations.AddField(
            model_name='church',
            name='admin',
            field=models.ManyToManyField(to='BookingUssd.ChurchAdmin'),
        ),
        migrations.AddField(
            model_name='church',
            name='featured_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church_featured_update', to='BookingUssd.Update'),
        ),
    ]
