# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-21 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingUssd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='featured_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='church_featured_update', to='BookingUssd.Update'),
        ),
    ]
