# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-21 19:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BookingUssd', '0002_auto_20171121_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='booking_action_label',
            field=models.CharField(blank=True, default='Book Appointment', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='updates_action_label',
            field=models.CharField(blank=True, default='Latest Updates', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='banking_details',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='contact_details',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='ussd_string',
            field=models.CharField(default=datetime.datetime(2017, 11, 21, 19, 10, 52, 206213, tzinfo=utc), max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
