# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-21 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingUssd', '0004_church_booking_subject_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='booking_subject_label',
            field=models.TextField(blank=True, default='What would you like to discuss?', max_length=150, null=True),
        ),
    ]
