# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-21 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingUssd', '0005_auto_20171121_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='address',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='banking_details',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='booking_action_label',
            field=models.TextField(blank=True, default='Book Appointment', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='contact_details',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='updates_action_label',
            field=models.TextField(blank=True, default='Latest Updates', max_length=150, null=True),
        ),
    ]
