# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-22 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingUssd', '0006_auto_20171121_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='booking_message_label',
            field=models.TextField(blank=True, default='When and where?', max_length=150, null=True),
        ),
    ]
