# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-23 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingUssd', '0011_auto_20171122_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchadmin',
            name='notification_msisdn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
