# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-26 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingUssd', '0012_churchadmin_notification_msisdn'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='churchadmin',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='admin',
            field=models.ManyToManyField(blank=True, null=True, to='BookingUssd.ChurchAdmin'),
        ),
    ]
