# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-26 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingUssd', '0013_auto_20171126_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='admin',
            field=models.ManyToManyField(blank=True, to='BookingUssd.ChurchAdmin'),
        ),
    ]
