# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-26 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingUssd', '0014_auto_20171126_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussdsession',
            name='request',
            field=models.TextField(max_length=5000),
        ),
    ]
