# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingUssd', '0017_auto_20171126_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='fetch_url',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='update',
            name='url',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
