# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingUssd', '0018_auto_20180126_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BookingUssd.Update'),
        ),
    ]
