# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-29 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingUssd', '0019_update_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
