# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-29 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingUssd', '0020_update_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='booking_submission_message'
        ),    
        migrations.AddField(
            model_name='church',
            name='booking_submission_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_update', to='BookingUssd.Update'),
        ),
    ]
