# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-29 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingUssd', '0021_auto_20180129_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='notify_requester',
            field=models.BooleanField(default=False),
        ),
    ]
