# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-29 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingUssd', '0022_church_notify_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='booking_url',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
