# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-29 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingUssd', '0023_church_booking_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='fetch_url',
            field=models.BooleanField(default=False),
        ),
    ]
