# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-29 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingUssd', '0024_church_fetch_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='church',
            name='booking_url',
        ),
        migrations.RemoveField(
            model_name='church',
            name='fetch_url',
        ),
    ]
